### ISSUE TITLE
Simple_Prep_docker not running on MacOS 10.12.3 (Sierra) ? 

### ISSUE THREAD

**Issue by jbpoline** [ReproNim/simple_workflow#17]
Trying Simple_Prep_docker jessie on Dave new mac  : seems that readlink, sed ...etc have different options. Bash looks lie 3.2.57 while my machine would 4.3.46(1)-release (x86_64-pc-linux-gnu)
Installing bash 4.?? and changing the shebang doesn't seem to help though...

**Comment by satra** [comment]
@jbpoline - the plan is to move completely to simply `docker pull run` - if one wants to recreate the environment outside of docker then we will provide some instructions but cannot be exhaustive across environments.

**Comment by jbpoline** [comment]
@satra  Yes, we thought about that as well - can we push the image be push to docker hub ?

**Comment by satra** [comment]
@jbpoline - yes - we will push to dockerhub - but i was hoping to do this after the weekend :)

**Comment by jbpoline** [comment]
@satra  Not sure the world will survive April 1st then ...:)
