### ISSUE TITLE
Docker could not download the files from NITRC

### ISSUE THREAD

**Issue by satra** [ReproNim/simple_workflow#26]
as reported in #15, @khinsen was unable to download the images from NITRC-IR. 

this was due to an issue where the server was down. and at this point appears to be operational again.

@khinsen - could you please give that command you used another try?

**Comment by khinsen** [comment]
The short test run for one participant works fine. I will try the longer one later.

**Comment by khinsen** [comment]
The full run ended up crashing my computer after a few days of computing. This is clearly Docker's fault - a container shouldn't be able to crash the host machine. But it means I cannot run the test to completion, so I will have to leave it at the short test run.

**Comment by dnkennedy** [comment]
I think the download problem was when NITRC was down for an extended period back in April.  This has been resolved, further tests have operated as expected, so I will close this.
