### ISSUE TITLE
FSL version in Docker

### ISSUE THREAD

**Issue by dnkennedy** [ReproNim/simple_workflow#27]
the readme in the build the docker container section says 'FSL 5.0.8-3', but the check_output.py reports 'Original FSL version: 5.0.9', which I thought was coming from the docker version.

**Comment by satra** [comment]
@dnkennedy - the README shows an example of how to create a docker container with a specific version of FSL released by a given date. the one we use is indeed 5.0.9

`./Simple_Prep_docker jessie 20170410T000000Z`

we can update the readme to indicate the the specific version used in the current Dockerfile. let me know. easy change to make.

**Comment by dnkennedy** [comment]
OK.  I think that update should be made to the README; as I think its good to have that be the instructions for how we built the docker we shared for this publication.

**Comment by satra** [comment]
done.
