### ISSUE TITLE
Question about accessing output of demo

### ISSUE THREAD

**Issue by cochrand** [ReproNim/simple_workflow#57]
I have run the demo on Docker in a Windows 10 environment, and I'm not sure how to go about accessing the output and checking it against published results. The output folder created is empty except for adding an empty folder labeled ";C".

**Comment by satra** [comment]
@cochrand - in general the docker version does everything inside the container. the only contact with the outside is through the volume mapping, which for windows will look quite different:

```
docker run -it --rm -v WINDOWS_PATH:/opt/repronim/simple_workflow/scripts/output \
   repronim/simple_workflow:latest run_demo_workflow.py \
   --key 11an55u9t2TAf0EV2pHN0vOd8Ww2Gie-tHp9xGULh_dA -n 1 
```

where `WINDOWS_PATH` would be something like: `C:/path/to/someplace` especially if you are using powershell.

and then the output from the docker would leave the outputs in `C:/path/to/someplace`

for some more info see this blog post: https://rominirani.com/docker-on-windows-mounting-host-directories-d96f3f056a2c

**Comment by cochrand** [comment]
OK, there seems to be problems with mounting directory. I pulled the alpine linux image to be able to follow exactly the blog you posted. When I tried to do Step 6: 
________________________________________________________________________________________________________
To mount our host directory (d:\data) in a container , we are going to use the -v (volume) flag while running the container. A sample run is shown here.

D:\>docker run -v d:/data:/data alpine ls /data
__________________________________________________________________________________________________________

When I ran the command:
docker run -v c:/Users/COchranD3/Documents/Docker/data:/data alpine ls /data

I got the error:
ls: C:/Program Files/Git/data: No such file or directory

Don't know why it's trying to go to Program Files/Git directory. Would this be because I'm using the Git Bash shell to run docker?

**Comment by cochrand** [comment]
Was able to resolve this by using Powershell instead of Git Bash shell. Working ok now. Will close issue
