### ISSUE TITLE
CircleCI 

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/simple_workflow#6]
1. seems that it is in Failing state for that last 6 months -- there is no "MATCH"
2. I do not see any report back from circleci for any PR -- is that anyhow enabled?

**Comment by satra** [comment]
intent is to leave in failing state. it does not match the expected output produced by aws instance.

**Comment by yarikoptic** [comment]
so the only utility for this CI setup then is just a one time pony show? kinda useless... I would have even argued to swap and make CI result references while AWS a "failing" one ;)  but ok -- just whining, feel free to close I guess

**Comment by satra** [comment]
this has been fixed as well with docker as reference.
