### ISSUE TITLE
"Fail early, behave deterministically" etc thoughts on Simple_Prep.sh

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/simple_workflow#7]
see https://github.com/ReproNim/module-reproducible-basics/blob/gh-pages/_episodes/01-shell-basics.md#fail-early-behave-deterministically while looking into  Simple_Prep.sh

I have following concerns about "Setup your own environment"

- what if I do have miniconda.sh which contains my GPG-encrypted secret bank code where I keep the 100,000,000$ I have earned do so well paid Debian development? (so - cd /tmp might be advisable or smth like that)

- if any step fails (I was told to have only FSL, but `unzip` was not present so there was fast scrolled away kaboom!!!) script keeps going until finishes neatly and I have no run_demo_workflow.py to run

- guarding with set -eu becomes tricky since script mixes two things -- preparation of the environment and demanded sourcing  of it.  I would suggest to split it into a script which doesn't need to be sourced and giving explicit sourcing command or another script

**Comment by satra** [comment]
those are good observations - install scripts need to be more robust (for v2 with niceman :) )

**Comment by satra** [comment]
all of these concerns have been addressed in current scripts.
