### ISSUE TITLE
provide/store more detailed information about dependency (FSL)

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/simple_workflow#8]
minor whining, feel free to close ;) :
Currently output of check_output.py states
```
Original platform: Linux-3.2.0-98-virtual-x86_64-with-debian-wheezy-sid
Original FSL version: 5.0.9
Current platform: Linux-4.9.0-rc2+-x86_64-with-debian-jessie-sid
Current FSL version: 5.0.9
```
somewhat suggesting to a naive observer that the reason is a different kernel, althought it is probably the platform's core libraries or a build of FSL (could have had a different minor revision etc).
Sure thing everything will be eventually improved, I just thought to note that quick enhancement could be done to grasp more detailed information about FSL at least.

**Comment by satra** [comment]
we rely on FSL providing this info, rather than say debian, which is limited to that version number.

**Comment by satra** [comment]
unless we can come up with a better platform independent way of getting FSL version, closing this for now. also the docker image builder and image should capture the specific version w.r.t. neurodebian.
